EXP_NJ_DMV_MTHLY_MERGE_DATA AS (
    SELECT 
        JNR_HEADER_DETAIL.DMV_VIN,
        JNR_HEADER_DETAIL.DMV_DRIVER_LICENSE_NUMBER,
        JNR_HEADER_DETAIL.DMV_MAKE_OF_CAR,
        JNR_HEADER_DETAIL.DMV_YEAR_OF_CAR,
        JNR_HEADER_DETAIL.DMV_MODEL_OF_CAR,
        JNR_HEADER_DETAIL.DMV_INS_COMPANY_CD,
        JNR_HEADER_DETAIL.DMV_POLICY_OWNER_STREET_ADDR,
        JNR_HEADER_DETAIL.DMV_POICY_OWNER_CITY,
        JNR_HEADER_DETAIL.DMV_POLICY_OWNER_STATE,
        JNR_HEADER_DETAIL.DMV_POLICY_OWNER_ZIP_CODE,
        JNR_HEADER_DETAIL.DMV_TRANSACTION_TYPE_CODE,
        JNR_HEADER_DETAIL.DMV_POLICY_EFFECTIVE_DATE,
        JNR_HEADER_DETAIL.DMV_POLICY_CANCELLATION_DATE,
        JNR_HEADER_DETAIL.DMV_DATE_STAMP,
        JNR_HEADER_DETAIL.DMV_POLICY_NUMBER,
        JNR_HEADER_DETAIL.source_record_id,
        JNR_HEADER_DETAIL.DMV_ORIG_DUE_DATE,
        JNR_HEADER_DETAIL.DMV_REC_TYPE_SORT_ORDER,
        JNR_HEADER_DETAIL.ROW_ORIGIN,
        JNR_HEADER_DETAIL.VERSION_NBR,
        JNR_HEADER_DETAIL.DMV_RESERVED,
        JNR_HEADER_DETAIL.CREATE_DATE,
        JNR_HEADER_DETAIL.MAPPING_NAME,
        UPPER(DMV_VIN) AS DMV_VIN_upper,
        TO_CHAR(TO_DATE(JNR_HEADER_DETAIL.DMV_ORIG_DUE_DATE), 'MMDDYYYY') AS DMV_ORIG_DUE_DATE_OUT,
        RPAD(DMV_VIN_upper, 19, ' ') AS OUT_DMV_VIN,
        RPAD(DMV_DRIVER_LICENSE_NUMBER, 15, ' ') AS OUT_DMV_DRIVER_LICENSE_NUMBER,
        RPAD(DMV_MAKE_OF_CAR, 5, ' ') AS OUT_DMV_MAKE_OF_CAR,
        RPAD(DMV_YEAR_OF_CAR, 4, ' ') AS OUT_DMV_YEAR_OF_CAR,
        RPAD(DMV_MODEL_OF_CAR, 5, ' ') AS OUT_DMV_MODEL_OF_CAR,
        RPAD(DMV_INS_COMPANY_CD, 4, ' ') AS OUT_DMV_INS_COMPANY_CD,
        RPAD(DMV_POLICY_OWNER_STREET_ADDR, 30, ' ') AS OUT_DMV_POLICY_OWNER_STREET_ADDR,
        RPAD(DMV_POICY_OWNER_CITY, 20, ' ') AS OUT_DMV_POICY_OWNER_CITY,
        RPAD(DMV_POLICY_OWNER_STATE, 2, ' ') AS OUT_DMV_POLICY_OWNER_STATE,
        RPAD(DMV_POLICY_OWNER_ZIP_CODE, 9, ' ') AS OUT_DMV_POLICY_OWNER_ZIP_CODE,
        RPAD(DMV_TRANSACTION_TYPE_CODE, 1, ' ') AS OUT_DMV_TRANSACTION_TYPE_CODE, -- Adding this field for later use
        RPAD(DMV_POLICY_EFFECTIVE_DATE, 8, ' ') AS OUT_DMV_POLICY_EFFECTIVE_DATE,
        RPAD(DMV_POLICY_CANCELLATION_DATE, 8, ' ') AS OUT_DMV_POLICY_CANCELLATION_DATE,
        RPAD(DMV_DATE_STAMP, 8, ' ') AS OUT_DMV_DATE_STAMP,
        RPAD(DMV_POLICY_NUMBER, 30, ' ') AS OUT_DMV_POLICY_NUMBER,
        TO_CHAR(CURRENT_TIMESTAMP, 'HHMMSS') AS DMV_TIME_STAMP,
        TO_CHAR(CURRENT_TIMESTAMP, 'MMDDYYYY') AS DMV_DATE_STAMP1,
        'NJ_DMV_DW' AS BUREAU_CD,
        'Y' AS CURRENT_BATCH_CYCLE_IND,
        'NJ' AS SRCE_SYS_CD,
        LKP_CYCLE_DUE_DATE.BATCH_END_DT
    FROM 
        JNR_HEADER_DETAIL
    LEFT JOIN (
        SELECT 
            BATCH_END_DT,
            BUREAU_CD,
            CURRENT_BATCH_CYCLE_IND,
            SRCE_SYS_CD,
            ROW_NUMBER() OVER(PARTITION BY BUREAU_CD, CURRENT_BATCH_CYCLE_IND, SRCE_SYS_CD ORDER BY BUREAU_CD, CURRENT_BATCH_CYCLE_IND, SRCE_SYS_CD) AS rn
        FROM 
            BURRPT.BATCH_BUILD_DATE_CTL
        QUALIFY 
            rn = 1
    ) LKP_CYCLE_DUE_DATE
    ON 
        LKP_CYCLE_DUE_DATE.BUREAU_CD = 'NJ_DMV_DW'
        AND LKP_CYCLE_DUE_DATE.CURRENT_BATCH_CYCLE_IND = 'Y'
        AND LKP_CYCLE_DUE_DATE.SRCE_SYS_CD = 'NJ'
),

INIT_TRAILER_VALUES AS (
    SELECT 
        source_record_id,
        OUT_DMV_INS_COMPANY_CD AS DMV_INS_COMPANY_CD,
        DMV_TIME_STAMP,
        DMV_DATE_STAMP1 AS DMV_DATE_STAMP,
        OUT_DMV_TRANSACTION_TYPE_CODE, -- Ensuring this is selected here
        1 AS INITIAL_TOTAL_RECORDS_COUNT,
        IFF(OUT_DMV_TRANSACTION_TYPE_CODE = 'N', 1, 0) AS INITIAL_TOTAL_NEW_POLICIES,
        IFF(OUT_DMV_TRANSACTION_TYPE_CODE = 'C', 1, 0) AS INITIAL_TOTAL_CANCELLED_POLICIES,
        RPAD('TRAILER', 7, ' ') AS DMV_RECORD_NAME,
        RPAD(' ', 151, ' ') AS FILLER
    FROM EXP_NJ_DMV_MTHLY_MERGE_DATA
),

AGG_TRAILER_VALUES AS (
    SELECT 
        source_record_id,
        DMV_INS_COMPANY_CD,
        DMV_TIME_STAMP,
        DMV_DATE_STAMP,
        OUT_DMV_TRANSACTION_TYPE_CODE, -- Adding this field here
        SUM(INITIAL_TOTAL_RECORDS_COUNT) OVER () AS TOTAL_RECORDS_COUNT_V,
        SUM(INITIAL_TOTAL_NEW_POLICIES) OVER () AS TOTAL_NEW_POLICIES_V,
        SUM(INITIAL_TOTAL_CANCELLED_POLICIES) OVER () AS TOTAL_CANCELLED_POLICIES_V,
        DMV_RECORD_NAME,
        FILLER
    FROM INIT_TRAILER_VALUES
),

EXP_NJ_DMV_MTHLY_MERGE_TRAILER_FF AS (
    SELECT 
        source_record_id,
        DMV_INS_COMPANY_CD,
        DMV_TIME_STAMP,
        DMV_DATE_STAMP,
        OUT_DMV_TRANSACTION_TYPE_CODE, -- Adding this field here for final selection
        LPAD(TOTAL_RECORDS_COUNT_V + 2, 8, '0') AS TOTAL_RECORDS_COUNT,
        TOTAL_NEW_POLICIES_V AS TOTAL_NEW_POLICIES,
        TOTAL_CANCELLED_POLICIES_V AS TOTAL_CANCELLED_POLICIES,
        DMV_RECORD_NAME,
        FILLER,
        DMV_RECORD_NAME || DMV_INS_COMPANY_CD || DMV_TIME_STAMP || DMV_DATE_STAMP || 
        LPAD(TOTAL_RECORDS_COUNT_V, 8, '0') || LPAD(TOTAL_NEW_POLICIES_V, 8, '0') || 
        LPAD(TOTAL_CANCELLED_POLICIES_V, 8, '0') || FILLER AS TRAILER
    FROM AGG_TRAILER_VALUES
)
