FROM Exp_Inputs_before_agg_DW AS T0
-- Writing query for unconnected lookup function
LEFT JOIN (
    SELECT 
        COUNT(*) AS COV_COUNT,
        h.POL_PK AS POL_PK,
        h.ORIG_POL_PK AS ORIG_POL_PK,
        LTRIM(RTRIM(h.PREMIUM_SOURCE_C)) AS PREMIUM_SOURCE_C,
        ROW_NUMBER() OVER (
            PARTITION BY h.POL_PK, h.ORIG_POL_PK, LTRIM(RTRIM(h.PREMIUM_SOURCE_C))
            ORDER BY h.POL_PK, h.ORIG_POL_PK, LTRIM(RTRIM(h.PREMIUM_SOURCE_C))
        ) AS rn
    FROM BURRPT.S10_ISO_PLOTA_EXTRACT_NE h
    GROUP BY 
        h.POL_PK,
        h.ORIG_POL_PK,
        LTRIM(RTRIM(h.PREMIUM_SOURCE_C))
    QUALIFY rn = 1
) lkp10
ON lkp10.POL_PK = T0.in_POL_PK
   AND lkp10.ORIG_POL_PK = T0.in_ORIG_POL_PK
   AND lkp10.PREMIUM_SOURCE_C = T0.in_PREMIUM_SOURCE_C
LEFT JOIN (
    SELECT 
        COUNT(*) AS COV_COUNT,
        h.POL_PK AS POL_PK,
        h.ORIG_POL_PK AS ORIG_POL_PK,
        LTRIM(RTRIM(h.PREMIUM_SOURCE_C)) AS PREMIUM_SOURCE_C,
        ROW_NUMBER() OVER (
            PARTITION BY h.POL_PK, h.ORIG_POL_PK, LTRIM(RTRIM(h.PREMIUM_SOURCE_C))
            ORDER BY h.POL_PK, h.ORIG_POL_PK, LTRIM(RTRIM(h.PREMIUM_SOURCE_C))
        ) AS rn
    FROM BURRPT.S10_ISO_PLOTA_EXTRACT_NE h
    GROUP BY 
        h.POL_PK,
        h.ORIG_POL_PK,
        LTRIM(RTRIM(h.PREMIUM_SOURCE_C))
    QUALIFY rn = 1
) lkp11
ON lkp11.POL_PK = T0.in_POL_PK
   AND lkp11.ORIG_POL_PK = T0.in_ORIG_POL_PK
   AND lkp11.PREMIUM_SOURCE_C = T0.in_PREMIUM_SOURCE_C
